src/main/resources/templates/fragment/footer.html
src/main/resources/templates/index.html
src/main/resources/templates/layout/default_layout.html

Test : full request test

---

src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/company-join.html

fix : thymeleaf 적용

---

src/main/java/com/miracle/memberservice/controller/CompanyController.java
src/main/java/com/miracle/memberservice/controller/GuestController.java
src/main/java/com/miracle/memberservice/controller/UserController.java
src/main/java/com/miracle/memberservice/controller/WindowController.java
src/main/java/com/miracle/memberservice/controller/json/JsonController.java
src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/company-join.html
src/main/resources/templates/user-join.html

회원가입 페이지 (유저, 기업 )
- 주소 api
- 비밀번호 일치 확인
- 사업자번호 인증 전송 (테스트, 아직 미완성)
- 재정의 버튼 스타일 적용

feat : join-page

---

src/main/java/com/miracle/memberservice/controller/CompanyController.java
src/main/java/com/miracle/memberservice/controller/GuestController.java
src/main/java/com/miracle/memberservice/controller/UserController.java
src/main/java/com/miracle/memberservice/controller/WindowController.java
src/main/java/com/miracle/memberservice/controller/json/JsonController.java
src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/company-join.html
src/main/resources/templates/user-join.html

feat : bno

---

src/main/java/com/miracle/memberservice/controller/CompanyController.java
src/main/java/com/miracle/memberservice/controller/json/JsonController.java
src/main/resources/templates/guest/company-join.html
src/main/resources/templates/user-join.html

design 수정
- 비밀번호
- 비밀번호 입력 안내문 위치, 구성 수정
- 사진파일 첨부 입력칸 추가

design : 기업 회원가입 수정

---

src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/company/post-form.html
src/main/resources/templates/guest/company-join.html

design : 공고 생성 페이지 완성 (디자인 미적용)

design : 공고 생성 페이지 완성 (디자인 미적용)

---

src/main/java/com/miracle/memberservice/controller/UserController.java
src/main/resources/templates/user/cover-letter.html
src/main/resources/templates/user/coverLetterForm.html
src/main/resources/templates/user/resumeForm.html
src/main/resources/templates/user/resumeList.html

design : 자기소개서 폼

---

src/main/java/com/miracle/memberservice/dto/response/JobResponseDto.java
src/main/java/com/miracle/memberservice/dto/response/StackResponseDto.java
src/main/java/com/miracle/memberservice/dto/response/UserBaseInfoResponseDto.java
src/main/java/com/miracle/memberservice/service/UserService.java
src/main/java/com/miracle/memberservice/util/ApiResponseToList.java
src/main/java/com/miracle/memberservice/util/Const.java
src/main/java/com/miracle/memberservice/util/ServiceCall.java
src/main/resources/templates/fragment/header.html
src/main/resources/templates/user/resume-list.html

이력서 폼 이동
- 유저 기본 정보 입력은 완성
- 직무, 스택은 admin에서 담아왔으나 service 클래스에서 dto로 담지 못함.

feat : 이력서 서비스 직무 스택 적용(미완성)

---

src/main/java/com/miracle/memberservice/controller/AdminController.java
src/main/java/com/miracle/memberservice/dto/response/JobResponseDto.java
src/main/java/com/miracle/memberservice/dto/response/StackResponseDto.java
src/main/java/com/miracle/memberservice/dto/response/UserBaseInfoResponseDto.java
src/main/java/com/miracle/memberservice/service/UserService.java
src/main/java/com/miracle/memberservice/util/ApiResponseToList.java
src/main/java/com/miracle/memberservice/util/Const.java
src/main/java/com/miracle/memberservice/util/ServiceCall.java
src/main/resources/templates/admin/login.html
src/main/resources/templates/admin/stackList.html
src/main/resources/templates/fragment/header.html
src/main/resources/templates/user/resume-list.html
src/main/resources/templates/user/resumeForm.html

Design : admin

---

src/main/java/com/miracle/memberservice/controller/AdminController.java
src/main/java/com/miracle/memberservice/controller/CompanyController.java
src/main/java/com/miracle/memberservice/controller/GuestController.java
src/main/java/com/miracle/memberservice/controller/IndexController.java
src/main/java/com/miracle/memberservice/controller/UserController.java
src/main/java/com/miracle/memberservice/dto/response/MainPagePostsResponseDto.java
src/main/java/com/miracle/memberservice/service/CompanyService.java
src/main/java/com/miracle/memberservice/service/UserService.java
src/main/java/com/miracle/memberservice/util/ApiResponseToList.java
src/main/resources/templates/company/post-list.html
src/main/resources/templates/guest/search-post.html
src/main/resources/templates/index.html

Feat: mainPage User/Company complete

---

src/main/java/com/miracle/memberservice/controller/MyPageController.java
src/main/java/com/miracle/memberservice/dto/request/CompanyInfoRequestDto.java
src/main/java/com/miracle/memberservice/dto/request/UserUpdateInfoRequestDto.java
src/main/java/com/miracle/memberservice/service/MyPageService.java
src/main/resources/templates/company/company-info.html
src/main/resources/templates/user/modify-form.html
src/main/resources/templates/user/resume-detail.html
src/main/resources/templates/user/user-info.html
src/main/resources/templates/user/validation.html

- 유저 개인정보 조회, 수정 완료
- 비밀번호 null 일때 기존 정보 넘기기 해결
- 기업 쪽은 아직 해결 안 된 상태입니다.

Feat : 유저 개인정보 조회, 수정 완료

---

build.gradle
src/main/java/com/miracle/memberservice/config/WebConfig.java
src/main/java/com/miracle/memberservice/controller/AdminController.java
src/main/java/com/miracle/memberservice/controller/CompanyController.java
src/main/java/com/miracle/memberservice/controller/GuestController.java
src/main/java/com/miracle/memberservice/controller/UserController.java
src/main/java/com/miracle/memberservice/dto/request/CommonTokenRequestDto.java
src/main/java/com/miracle/memberservice/dto/request/CompanyTokenRequestDto.java
src/main/java/com/miracle/memberservice/dto/request/UserTokenRequestDto.java
src/main/java/com/miracle/memberservice/dto/token/AbstractToken.java
src/main/java/com/miracle/memberservice/dto/token/AccessToken.java
src/main/java/com/miracle/memberservice/filter/TokenFilter.java
src/main/java/com/miracle/memberservice/service/TokenService.java
src/main/java/com/miracle/memberservice/service/TokenServiceImpl.java

1. 로그아웃 시 쿠키에 저장된 토큰 삭제
2. 메인 페이지 접근 시 쿠키에 토큰이 없으면 로그인이 유지되지 않음
3. 로그인 후 브라우저를 닫았다가 켜도 로그인 상태 유지됨
4. 브라우저를 닫았다가 켜면 토큰에 담긴 정보를 세션에 넣어줌

[TokenFilter] TokenService 구현

---

src/main/resources/templates/guest/user-login.html

Feat: SSO 로그인 이동 구현

---

src/main/java/com/miracle/memberservice/filter/TokenFilter.java

refactor/tokenFilter -> feature

Refactor: tokenFilter 세션 삭제 로직 추가

---

src/main/java/com/miracle/memberservice/controller/GuestController.java
src/main/resources/templates/index.html

Refactor: 기업 회원 일때만 차트 draw 하도록 수정

---

src/main/resources/templates/admin/main.html
src/main/resources/templates/guest/google-join.html
src/main/resources/templates/guest/user-join.html

- 메인페이지 그라파나 url 변경
- 관리자 헤더 변경

FIX : admin main, header

---

src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/admin/job-list.html
src/main/resources/templates/admin/join-count.html
src/main/resources/templates/admin/stack-list.html
src/main/resources/templates/fragment/admin-header.html
src/main/resources/templates/user/resumes.html

- 직무 / 스택 디자인 요구사항 반영
- 폰트사이즈 / 버튼 위치 조정

Fix : 디자인 수정

---

src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/fragment/header.html
src/main/resources/templates/guest/search-post.html
src/main/resources/templates/index.html
src/main/resources/templates/user/additional-info.html

- 회원가입 버튼 헤더 -> 메인 페이지 롤백
- 메인 페이지 줄바꿈 폰트 사이즈 조정
- 구글 로그인 전화번호 인증번호 입력칸 복구
-

Fix - 회원가입 버튼 위치 변경 / custom-block 경력 신입 추가, 폰트 사이즈 조정

---

src/main/resources/static/css/templatemo-pod-talk.css
src/main/resources/templates/admin/company-join-count.html
src/main/resources/templates/admin/company-list.html
src/main/resources/templates/admin/job-list.html
src/main/resources/templates/admin/stack-list.html
src/main/resources/templates/admin/user-join-count.html

직무/ 기술스택 폰트사이즈 조정
가운데 정렬 적용
구글 차트 버튼 위치 조정

Fix - 관리자 페이지 수정

---

src/main/resources/templates/admin/job-list.html
src/main/resources/templates/admin/stack-list.html

Fix : 관리자 스택/직무 등록 시 잘못된 예외 처리 수정

---

src/main/resources/templates/admin/job-list.html
src/main/resources/templates/admin/stack-list.html

fix -> develop
- 직무/스택 등록 시, alert창 문구 변경 및 location reload

스택/직무 등록 시 예외 처리 수정

---

src/main/resources/templates/admin/job-list.html

[x] 직무 수정 시 오류 해결
fix/joblist -> develop

직무 수정 오류 해결

---

src/main/resources/templates/admin/job-list.html

[x] 직무 placeholder 잘못 기입되어 있는 멘트 변경
fix/job-list -> develop

직무 placeholder 멘트 수정
